### ISSUE TITLE
Support audit criticality levels for application

### ISSUE THREAD

**Issue by harti2006** [zalando-stups/kio#12]
Each application should have an audit criticality level 1, 2 or 3.
1: Not audit relevant
2: Audit relevant
3: PCI

The criticality level defines the number of required approvers (Level 1 -> 1 Approver, Level 2 and 3 -> 2 approvers)

The default value for each new application is 2. Only a few people should be able to change this.

**Comment by hjacobs** [comment]
We should not hardcode such criticality levels in Kio, is there a better solution?

**Comment by harti2006** [comment]
this is just an interim solution, until we can map criticality to OAuth scopes. It is needed for Tech Controlling to filter relevant apps.
