### ISSUE TITLE
Allow a robot user to make and approve new versions

### ISSUE THREAD

**Issue by dmitrykrivaltsevich** [zalando-stups/kio#17]
Our team would like to fully automate our continuous delivery process. At the moment Kio API doesn't allow robot user (our Jenkins robot user) with realm "services" to make and approve new versions in Kio. Would be nice to have this ability.

**Comment by dmitrykrivaltsevich** [comment]
Comments from Henning Jacobs:

talk to STUPS (Andre), I think Kio should respect the application.write_all scope
(like Pier One)

**Comment by prayerslayer** [comment]
Tracked with #28
