### ISSUE TITLE
Extend [/apps] endpoint to return only apps registered after a certain timestap

### ISSUE THREAD

**Issue by kanuku** [zalando-stups/kio#23]
zalando/kontrolletti#12 Is a job responsible for importing scm-url's from new applications registered with `zalando-stups/kio`.
Can you extend the `/apps`-endpoint to accept a `timestamp` filter parameter such that we could request only for applications registered/updated after a certain time? 
The result should only contain apps that were updated or created after the passed `timestamp`parameters.

**Comment by prayerslayer** [comment]
As an alternative and quick fix, would it also be feasible for you if we include the `created` field to the response of `/apps`? Then you could filter yourself.

In general I think it’s a good idea to provide more filter options.

**Comment by hjacobs** [comment]
@prayerslayer the last_modified timestamp would need to be included, too

**Comment by kanuku** [comment]
@prayerslayer yes, the alternative quick fix is fine(including `last_modified` field). 
Thank you in advance :+1: !!

**Comment by prayerslayer** [comment]
Then the proposal #22 would fix this one too, awesome.
