### ISSUE TITLE
Kio update app/app version error

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/kio#31]
Boolean field have no default and maybe wrong mapped. rest api/sql should be fixed.

**Comment by prayerslayer** [comment]
I don't remember what this was about. Is this still an issue?

**Comment by mrandi** [comment]
I'm not sure the mapping was the problem or only the default value for boolean fields. I think I solved with an explicit value.

**Comment by prayerslayer** [comment]
I think there was something wrong with your JSON serialization, maybe?

In any case as this issue appears to be solved, I'll close it.
