### ISSUE TITLE
Support release stages workflow

### ISSUE THREAD

**Issue by nsmolenskii** [zalando-stups/kio#32]
**As** Release-engineer 
**I want** reduce redundant steps while deploying new version on release stage 
**So that** reduce deploy time for new version on release stage and keep me audit compliant

**Currently every single time when I deploy release stage I could receive a lot of violations:**
- APPLICATION_VERSION_NOT_PRESENT_IN_KIO
- MISSING_VERSION_APPROVAL
- VERSION_APPROVAL_NOT_ENOUGH
- EC2_WITH_A_SNAPSHOT_IMAGE

**To be audit compliant I should have no violations at all.**

**To deploy new version into release stage without violations I should:**
- _Manually create a version_
- _Approve the version version_
- _Ask at least one colleague to approve the version_
- **Make a deployment**
- _Go to violations and resolve EC2_WITH_A_SNAPSHOT_IMAGE manually_

**Unfortunately, only one of these steps makes sense for release stages**

**Comment by hjacobs** [comment]
I think you want to file this issue on the Fullstop component, not Kio :smirk:

**Comment by nsmolenskii** [comment]
Thank You @hjacobs

**Comment by nsmolenskii** [comment]
moved into zalando-stups/fullstop#255
