### ISSUE TITLE
Produce only violations that make sense

### ISSUE THREAD

**Issue by nsmolenskii** [zalando-stups/kio#33]
**As** Deploy engineer
**I want** to see violations that make sense
**So that** reduce violations count and make process much cleaner

**Currently I could receive these violations together**:
- MISSING_VERSION_APPROVAL
- VERSION_APPROVAL_NOT_ENOUGH

**Unfortunately second one has no matter if first one already presented**

**Comment by hjacobs** [comment]
I think you want to file this issue on the Fullstop component, not Kio :smirk:

**Comment by nsmolenskii** [comment]
Thank You @hjacobs

**Comment by nsmolenskii** [comment]
moved into zalando-stups/fullstop#254
