### ISSUE TITLE
Increase Hystrix timeouts

### ISSUE THREAD

**Issue by harti2006** [zalando-stups/kio#34]
The default timeout period of one second is too short and leads to 503 response status occurring very often. 

I suggest to increase it to 1.5 or 2 seconds and see if it helps.

**Comment by hjacobs** [comment]
FYI: Hystrix timeouts are currently disabled in Pier One

**Comment by sarnowski** [comment]
Is that a scalable solution? Shouldn't we make sure that nothing takes longer than a second in the first place?
