### ISSUE TITLE
Allow service users to create applications

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/kio#36]
But safely without god mode, ie. only for their team, same as humans.

**Comment by hjacobs** [comment]
we should move the Pier One logic (which is exactly what you need) to Friboo: https://github.com/zalando-stups/pierone/blob/master/src/org/zalando/stups/pierone/api_v1.clj#L88

**Comment by prayerslayer** [comment]
Good idea!

**Comment by prayerslayer** [comment]
Requires zalando-stups/friboo#36
