### ISSUE TITLE
Application version must be immutable

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/kio#41]
Change PUT method to a PUT idempotent as the application version must be immutable

**Comment by sarnowski** [comment]
Whats the reasoning here? Why ist POST immutable and PUT is not?

**Comment by hjacobs** [comment]
Yes, please keep PUT (idempotent) and make sure that a repeated PUT works if the content is the same and will throw an error if the content is different (immutability).

**Comment by mrandi** [comment]
PUT idempotent is perfect!

Thought POST as a create but you are right PUT idempotent is better.

@sarnowski because right now the PUT also do an update and remove all approvals.

**Comment by sarnowski** [comment]
Yes, that was actually the initial idea. If you change something in the version information, all previous approvals are invalid are are removed.

**Comment by mrandi** [comment]
so we have not an immutable version, and that is the point. Or?

**Comment by hjacobs** [comment]
hmm, it should be immutable!

**Comment by hjacobs** [comment]
Versions were removed.
