### ISSUE TITLE
Allow /apps to be filtered by team

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/kio#46]
This would help for zalando-stups/yourturn#386 and general curl usage.

**Comment by lotharschulz** [comment]
+1

so far a workaround to get all items per team could be:

```
curl --header "Authorization: Bearer [myToken]"  https://kio.stups.zalan.do/apps | jq '.[] | select(.team_id == "[teamid]")'
```

**Comment by hjacobs** [comment]
:+1: obviously I would expect the `/apps` endpoint to accept "any" application field to filter by (or at least all fields which are indexed in the database).
