### ISSUE TITLE
org.postgresql.util.PSQLException: ERROR: syntax error in tsquery: "team:foobar"

### ISSUE THREAD

**Issue by harti2006** [zalando-stups/kio#48]
It seems that colons inside search queries produce the following postgresql exception:

`org.postgresql.util.PSQLException: ERROR: syntax error in tsquery: "team:octopus"`

**Comment by prayerslayer** [comment]
Just replace with pipes so that it at least doesn't break? (It still won't do what intended.)

**Comment by prayerslayer** [comment]
We should just use `plainto_tsquery` instead of `to_tsquery` as it handles all those "user input errors" (not really errors but you know what I mean) for us.

http://www.postgresql.org/docs/9.4/static/functions-textsearch.html
