### ISSUE TITLE
Load Testing fields in Kio/Yourturn

### ISSUE THREAD

**Issue by a1exmac** [zalando-stups/kio#81]
As we agreed in email, we would like to add 2 more fields in Kio/Yourturn about Load Testing.
**Field # 1 “Link to load test scripts”**
Which can have one of 3 values:
1. not yet: The application must be load tested, but they do not have a load testing tool yet. 
2. doesn't apply: The application doesn't need to be load tested, e.g. native application.
3. {Load_test_artefacts_URL}: GHE link to load test script when using scripted load testing tool / GHE link to load test configuration files when using non-scripted tool / link to internal docs that explain how to run those load tests when using a non-scripted tool. 
<img width="814" alt="screen shot 2017-06-26 at 16 33 14" src="https://user-images.githubusercontent.com/3379743/27544369-3711c8b4-5a8d-11e7-9b87-312dfd2ea119.png">

**Field # 2 “Request Per Second (RPS)”**
Will be added for each git revision id / docker image tag `git rev-parse HEAD | cut -c-10` meaning git rev id `671ee80c08` and can handle `80` RPS
<img width="733" alt="screen shot 2017-06-26 at 16 04 16" src="https://user-images.githubusercontent.com/3379743/27543064-5d277c3c-5a89-11e7-87e4-c96e72354e3f.png">

**Comment by elgalu** [comment]
We would also like the kio CLI to have a new sub-command `rps` within `version` like this

```
kio version rps ${application_id} ${app_ver} ${requests_per_second}
```

This way users can communicate the "Field # 2 “Request Per Second (RPS)” per application version.

To clarify:

1. `link_to_load_test_script` field is 1 per application
2. `requests_per_second` or `rps` field is 1 per application version

When we move out of Kio (if/when gets deprecated) we will seek out to store the same in the new app management solution.

**Comment by hjacobs** [comment]
We don't have plans to implement this right now.
